name: PublishLab

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ December2020 ]
  pull_request:
    branches: [ December2020 ]

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: $\{{secrets.TOKEN}}
          repository: rfcm83/.NET-Modernization-In-a-Day
          branch: master
          force: true